databases:
  - name: bread_quiz_db
    databaseName: bread_quiz_db
    user: bread_quiz
    region: singapore

services:
  - type: web
    name: bread_quiz
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bread_quiz_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false